/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComGithubGardenerGardenerPkgApisCoreV1beta1MachineImageVersion } from './comGithubGardenerGardenerPkgApisCoreV1beta1MachineImageVersion';


/**
 * MachineImage defines the name and multiple versions of the machine image in any environment.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1MachineImage { 
    /**
     * Name is the name of the image.
     */
    name: string;
    /**
     * UpdateStrategy is the update strategy to use for the machine image. Possible values are:  - patch: update to the latest patch version of the current minor version.  - minor: update to the latest minor and patch version.  - major: always update to the overall latest version (default).
     */
    updateStrategy?: string;
    /**
     * Versions contains versions, expiration dates and container runtimes of the machine image
     */
    versions: Array<ComGithubGardenerGardenerPkgApisCoreV1beta1MachineImageVersion>;
}

