/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DNSIncludeExclude contains information about which domains shall be included/excluded.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1DNSIncludeExclude { 
    /**
     * Exclude is a list of domains that shall be excluded.
     */
    exclude?: Array<string>;
    /**
     * Include is a list of domains that shall be included.
     */
    include?: Array<string>;
}

