/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ShootAdvertisedAddress contains information for the shoot\'s Kube API server.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1ShootAdvertisedAddress { 
    /**
     * Name of the advertised address. e.g. external
     */
    name: string;
    /**
     * The URL of the API Server. e.g. https://api.foo.bar or https://1.2.3.4
     */
    url: string;
}

