/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * GardenerResourceData holds the data which is used to generate resources, deployed in the Shoot\'s control plane.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1GardenerResourceData { 
    /**
     * Data contains the payload required to generate resources
     */
    data: object;
    /**
     * Labels are labels of the object
     */
    labels?: { [key: string]: string; };
    /**
     * Name of the object required to generate resources
     */
    name: string;
    /**
     * Type of the object
     */
    type: string;
}

