/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SecretBindingProvider defines the provider type of the SecretBinding.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1SecretBindingProvider { 
    /**
     * Type is the type of the provider.  For backwards compatibility, the field can contain multiple providers separated by a comma. However the usage of single SecretBinding (hence Secret) for different cloud providers is strongly discouraged.
     */
    type: string;
}

