/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * AdmissionPlugin contains information about a specific admission plugin and its corresponding configuration.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1AdmissionPlugin { 
    /**
     * Config is the configuration of the plugin.
     */
    config?: object;
    /**
     * Disabled specifies whether this plugin should be disabled.
     */
    disabled?: boolean;
    /**
     * KubeconfigSecretName specifies the name of a secret containing the kubeconfig for this admission plugin.
     */
    kubeconfigSecretName?: string;
    /**
     * Name is the name of the plugin.
     */
    name: string;
}

