/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComGithubGardenerGardenerPkgApisCoreV1beta1NamedResourceReference } from './comGithubGardenerGardenerPkgApisCoreV1beta1NamedResourceReference';


/**
 * ExtensionResourceState contains the kind of the extension custom resource and its last observed state in the Shoot\'s namespace on the Seed cluster.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1ExtensionResourceState { 
    /**
     * Kind (type) of the extension custom resource
     */
    kind: string;
    /**
     * Name of the extension custom resource
     */
    name?: string;
    /**
     * Purpose of the extension custom resource
     */
    purpose?: string;
    /**
     * Resources holds a list of named resource references that can be referred to in the state by their names.
     */
    resources?: Array<ComGithubGardenerGardenerPkgApisCoreV1beta1NamedResourceReference>;
    /**
     * State of the extension resource
     */
    state?: object;
}

