/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Extension contains type and provider information for Shoot extensions.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1Extension { 
    /**
     * Disabled allows to disable extensions that were marked as \'globally enabled\' by Gardener administrators.
     */
    disabled?: boolean;
    /**
     * ProviderConfig is the configuration passed to extension resource.
     */
    providerConfig?: object;
    /**
     * Type is the type of the extension resource.
     */
    type: string;
}

