/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComGithubGardenerGardenerPkgApisCoreV1beta1Toleration } from './comGithubGardenerGardenerPkgApisCoreV1beta1Toleration';


/**
 * ProjectTolerations contains the tolerations for taints on seed clusters.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1ProjectTolerations { 
    /**
     * Defaults contains a list of tolerations that are added to the shoots in this project by default.
     */
    defaults?: Array<ComGithubGardenerGardenerPkgApisCoreV1beta1Toleration>;
    /**
     * Whitelist contains a list of tolerations that are allowed to be added to the shoots in this project. Please note that this list may only be added by users having the `spec-tolerations-whitelist` verb for project resources.
     */
    whitelist?: Array<ComGithubGardenerGardenerPkgApisCoreV1beta1Toleration>;
}

