/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Networking defines networking parameters for the shoot cluster.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1Networking { 
    /**
     * IPFamilies specifies the IP protocol versions to use for shoot networking. This field is immutable. See https://github.com/gardener/gardener/blob/master/docs/usage/ipv6.md. Defaults to [\"IPv4\"].
     */
    ipFamilies?: Array<string>;
    /**
     * Nodes is the CIDR of the entire node network. This field is mutable.
     */
    nodes?: string;
    /**
     * Pods is the CIDR of the pod network. This field is immutable.
     */
    pods?: string;
    /**
     * ProviderConfig is the configuration passed to network resource.
     */
    providerConfig?: object;
    /**
     * Services is the CIDR of the service network. This field is immutable.
     */
    services?: string;
    /**
     * Type identifies the type of the networking plugin. This field is immutable.
     */
    type?: string;
}

