/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IoK8sApiAutoscalingV1CrossVersionObjectReference } from './ioK8sApiAutoscalingV1CrossVersionObjectReference';


/**
 * NamedResourceReference is a named reference to a resource.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1NamedResourceReference { 
    /**
     * Name of the resource reference.
     */
    name: string;
    /**
     * ResourceRef is a reference to a resource.
     */
    resourceRef: IoK8sApiAutoscalingV1CrossVersionObjectReference;
}

