/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ClusterAutoscalerOptions contains the cluster autoscaler configurations for a worker pool.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1ClusterAutoscalerOptions { 
    /**
     * MaxNodeProvisionTime defines how long CA waits for node to be provisioned.
     */
    maxNodeProvisionTime?: string;
    /**
     * ScaleDownGpuUtilizationThreshold defines the threshold in fraction (0.0 - 1.0) of gpu resources under which a node is being removed.
     */
    scaleDownGpuUtilizationThreshold?: number;
    /**
     * ScaleDownUnneededTime defines how long a node should be unneeded before it is eligible for scale down.
     */
    scaleDownUnneededTime?: string;
    /**
     * ScaleDownUnreadyTime defines how long an unready node should be unneeded before it is eligible for scale down.
     */
    scaleDownUnreadyTime?: string;
    /**
     * ScaleDownUtilizationThreshold defines the threshold in fraction (0.0 - 1.0) under which a node is being removed.
     */
    scaleDownUtilizationThreshold?: number;
}

