/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComGithubGardenerGardenerPkgApisCoreV1beta1WorkersSettings } from './comGithubGardenerGardenerPkgApisCoreV1beta1WorkersSettings';
import { ComGithubGardenerGardenerPkgApisCoreV1beta1Worker } from './comGithubGardenerGardenerPkgApisCoreV1beta1Worker';


/**
 * Provider contains provider-specific information that are handed-over to the provider-specific extension controller.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1Provider { 
    /**
     * ControlPlaneConfig contains the provider-specific control plane config blob. Please look up the concrete definition in the documentation of your provider extension.
     */
    controlPlaneConfig?: object;
    /**
     * InfrastructureConfig contains the provider-specific infrastructure config blob. Please look up the concrete definition in the documentation of your provider extension.
     */
    infrastructureConfig?: object;
    /**
     * Type is the type of the provider. This field is immutable.
     */
    type: string;
    /**
     * Workers is a list of worker groups.
     */
    workers?: Array<ComGithubGardenerGardenerPkgApisCoreV1beta1Worker>;
    /**
     * WorkersSettings contains settings for all workers.
     */
    workersSettings?: ComGithubGardenerGardenerPkgApisCoreV1beta1WorkersSettings;
}

