/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SeedTaint describes a taint on a seed.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1SeedTaint { 
    /**
     * Key is the taint key to be applied to a seed.
     */
    key: string;
    /**
     * Value is the taint value corresponding to the taint key.
     */
    value?: string;
}

