// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type IsAny<T> = 0 extends 1 & T ? true : false
type InjectionType<A extends Plugin> = IsAny<A> extends true ? unknown : A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/app/plugins/navigation-repaint.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/app/plugins/check-outdated-build.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.5.1_magicast@0.3.4_rollup@4.18.0_typescript@5.3.3_vue@3.4.31_typescript@5.3.3_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.1.4_@types+node@20.11.24_sass@1.71.1_terser@5.31.1_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.3.9_rollup@4.18.0_vite@5.1.4_@types+node@20.11.24_sass@1.71.1_terser@5.31.1_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/dayjs-nuxt@2.1.9_magicast@0.3.4_rollup@4.18.0/node_modules/dayjs-nuxt/dist/runtime/plugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+device@3.1.1_magicast@0.3.4_rollup@4.18.0/node_modules/@nuxtjs/device/dist/runtime/plugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/app/plugins/dev-server-logs").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.3_@parcel+watcher@2.4.1_@types+node@20.11.24_eslint@8.57.0_ioredis@5.4.1_magicast@0_aj6hnfu3ma3itqu5gxv2hxw67m/node_modules/nuxt/dist/app/plugins/check-if-layout-used").default> &
  InjectionType<typeof import("../../plugins/vuetify/index").default> &
  InjectionType<typeof import("../../plugins/iconify/index").default> &
  InjectionType<typeof import("../../plugins/layouts").default> &
  InjectionType<typeof import("../../plugins/webfontloader.client").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
