/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { OrganizationMember } from "./OrganizationMember";
import { OrganizationMemberCountArgs } from "./OrganizationMemberCountArgs";
import { OrganizationMemberFindManyArgs } from "./OrganizationMemberFindManyArgs";
import { OrganizationMemberFindUniqueArgs } from "./OrganizationMemberFindUniqueArgs";
import { CreateOrganizationMemberArgs } from "./CreateOrganizationMemberArgs";
import { UpdateOrganizationMemberArgs } from "./UpdateOrganizationMemberArgs";
import { DeleteOrganizationMemberArgs } from "./DeleteOrganizationMemberArgs";
import { Invitation } from "../../invitation/base/Invitation";
import { Organization } from "../../organization/base/Organization";
import { User } from "../../user/base/User";
import { OrganizationMemberService } from "../organizationMember.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => OrganizationMember)
export class OrganizationMemberResolverBase {
  constructor(
    protected readonly service: OrganizationMemberService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "OrganizationMember",
    action: "read",
    possession: "any",
  })
  async _organizationMembersMeta(
    @graphql.Args() args: OrganizationMemberCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [OrganizationMember])
  @nestAccessControl.UseRoles({
    resource: "OrganizationMember",
    action: "read",
    possession: "any",
  })
  async organizationMembers(
    @graphql.Args() args: OrganizationMemberFindManyArgs
  ): Promise<OrganizationMember[]> {
    return this.service.organizationMembers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => OrganizationMember, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "OrganizationMember",
    action: "read",
    possession: "own",
  })
  async organizationMember(
    @graphql.Args() args: OrganizationMemberFindUniqueArgs
  ): Promise<OrganizationMember | null> {
    const result = await this.service.organizationMember(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => OrganizationMember)
  @nestAccessControl.UseRoles({
    resource: "OrganizationMember",
    action: "create",
    possession: "any",
  })
  async createOrganizationMember(
    @graphql.Args() args: CreateOrganizationMemberArgs
  ): Promise<OrganizationMember> {
    return await this.service.createOrganizationMember({
      ...args,
      data: {
        ...args.data,

        invitation: args.data.invitation
          ? {
              connect: args.data.invitation,
            }
          : undefined,

        organization: {
          connect: args.data.organization,
        },

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => OrganizationMember)
  @nestAccessControl.UseRoles({
    resource: "OrganizationMember",
    action: "update",
    possession: "any",
  })
  async updateOrganizationMember(
    @graphql.Args() args: UpdateOrganizationMemberArgs
  ): Promise<OrganizationMember | null> {
    try {
      return await this.service.updateOrganizationMember({
        ...args,
        data: {
          ...args.data,

          invitation: args.data.invitation
            ? {
                connect: args.data.invitation,
              }
            : undefined,

          organization: {
            connect: args.data.organization,
          },

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => OrganizationMember)
  @nestAccessControl.UseRoles({
    resource: "OrganizationMember",
    action: "delete",
    possession: "any",
  })
  async deleteOrganizationMember(
    @graphql.Args() args: DeleteOrganizationMemberArgs
  ): Promise<OrganizationMember | null> {
    try {
      return await this.service.deleteOrganizationMember(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Invitation, {
    nullable: true,
    name: "invitation",
  })
  @nestAccessControl.UseRoles({
    resource: "Invitation",
    action: "read",
    possession: "any",
  })
  async getInvitation(
    @graphql.Parent() parent: OrganizationMember
  ): Promise<Invitation | null> {
    const result = await this.service.getInvitation(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Organization, {
    nullable: true,
    name: "organization",
  })
  @nestAccessControl.UseRoles({
    resource: "Organization",
    action: "read",
    possession: "any",
  })
  async getOrganization(
    @graphql.Parent() parent: OrganizationMember
  ): Promise<Organization | null> {
    const result = await this.service.getOrganization(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: OrganizationMember
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
