/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Cluster } from "./Cluster";
import { ClusterFindUniqueArgs } from "./ClusterFindUniqueArgs";
import { ClusterService } from "../cluster.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Cluster)
export class ClusterResolverBase {
  constructor(
    protected readonly service: ClusterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Cluster, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Cluster",
    action: "read",
    possession: "own",
  })
  async cluster(
    @graphql.Args() args: ClusterFindUniqueArgs
  ): Promise<Cluster | null> {
    const result = await this.service.cluster(args);
    if (result === null) {
      return null;
    }
    return result;
  }
}
