
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AppBarSearch': typeof import("../@core/components/AppBarSearch.vue")['default']
    'AppDrawerHeaderSection': typeof import("../@core/components/AppDrawerHeaderSection.vue")['default']
    'AppStepper': typeof import("../@core/components/AppStepper.vue")['default']
    'BuyNow': typeof import("../@core/components/BuyNow.vue")['default']
    'CardStatisticsVerticalSimple': typeof import("../@core/components/CardStatisticsVerticalSimple.vue")['default']
    'CustomizerSection': typeof import("../@core/components/CustomizerSection.vue")['default']
    'DialogCloseBtn': typeof import("../@core/components/DialogCloseBtn.vue")['default']
    'DropZone': typeof import("../@core/components/DropZone.vue")['default']
    'I18n': typeof import("../@core/components/I18n.vue")['default']
    'MoreBtn': typeof import("../@core/components/MoreBtn.vue")['default']
    'Notifications': typeof import("../@core/components/Notifications.vue")['default']
    'ProductDescriptionEditor': typeof import("../@core/components/ProductDescriptionEditor.vue")['default']
    'ScrollToTop': typeof import("../@core/components/ScrollToTop.vue")['default']
    'Shortcuts': typeof import("../@core/components/Shortcuts.vue")['default']
    'TablePagination': typeof import("../@core/components/TablePagination.vue")['default']
    'TheCustomizer': typeof import("../@core/components/TheCustomizer.vue")['default']
    'ThemeSwitcher': typeof import("../@core/components/ThemeSwitcher.vue")['default']
    'TiptapEditor': typeof import("../@core/components/TiptapEditor.vue")['default']
    'AppAutocomplete': typeof import("../@core/components/app-form-elements/AppAutocomplete.vue")['default']
    'AppCombobox': typeof import("../@core/components/app-form-elements/AppCombobox.vue")['default']
    'AppDateTimePicker': typeof import("../@core/components/app-form-elements/AppDateTimePicker.vue")['default']
    'AppSelect': typeof import("../@core/components/app-form-elements/AppSelect.vue")['default']
    'AppTextField': typeof import("../@core/components/app-form-elements/AppTextField.vue")['default']
    'AppTextarea': typeof import("../@core/components/app-form-elements/AppTextarea.vue")['default']
    'CustomCheckboxes': typeof import("../@core/components/app-form-elements/CustomCheckboxes.vue")['default']
    'CustomCheckboxesWithIcon': typeof import("../@core/components/app-form-elements/CustomCheckboxesWithIcon.vue")['default']
    'CustomCheckboxesWithImage': typeof import("../@core/components/app-form-elements/CustomCheckboxesWithImage.vue")['default']
    'CustomRadios': typeof import("../@core/components/app-form-elements/CustomRadios.vue")['default']
    'CustomRadiosWithIcon': typeof import("../@core/components/app-form-elements/CustomRadiosWithIcon.vue")['default']
    'AppCardActions': typeof import("../@core/components/cards/AppCardActions.vue")['default']
    'AppCardCode': typeof import("../@core/components/cards/AppCardCode.vue")['default']
    'CardStatisticsHorizontal': typeof import("../@core/components/cards/CardStatisticsHorizontal.vue")['default']
    'CardStatisticsVertical': typeof import("../@core/components/cards/CardStatisticsVertical.vue")['default']
    'AppLoadingIndicator': typeof import("../components/AppLoadingIndicator.vue")['default']
    'AppPricing': typeof import("../components/AppPricing.vue")['default']
    'AppSearchHeader': typeof import("../components/AppSearchHeader.vue")['default']
    'ErrorHeader': typeof import("../components/ErrorHeader.vue")['default']
    'FormStep': typeof import("../components/FormStep.vue")['default']
    'VueApexCharts': typeof import("../components/VueApexCharts.client.vue")['default']
    'AddAuthenticatorAppDialog': typeof import("../components/dialogs/AddAuthenticatorAppDialog.vue")['default']
    'AddEditAddressDialog': typeof import("../components/dialogs/AddEditAddressDialog.vue")['default']
    'AddEditPermissionDialog': typeof import("../components/dialogs/AddEditPermissionDialog.vue")['default']
    'AddEditRoleDialog': typeof import("../components/dialogs/AddEditRoleDialog.vue")['default']
    'AddEditVolume': typeof import("../components/dialogs/AddEditVolume.vue")['default']
    'AddKubeflowUserDialog': typeof import("../components/dialogs/AddKubeflowUserDialog.vue")['default']
    'AddMOrganizationemberDialog': typeof import("../components/dialogs/AddMOrganizationemberDialog.vue")['default']
    'AddPaymentMethodDialog': typeof import("../components/dialogs/AddPaymentMethodDialog.vue")['default']
    'CardAddEditDialog': typeof import("../components/dialogs/CardAddEditDialog.vue")['default']
    'ConfirmDialog': typeof import("../components/dialogs/ConfirmDialog.vue")['default']
    'CreateAppDialog': typeof import("../components/dialogs/CreateAppDialog.vue")['default']
    'EnableOneTimePasswordDialog': typeof import("../components/dialogs/EnableOneTimePasswordDialog.vue")['default']
    'PaymentProvidersDialog': typeof import("../components/dialogs/PaymentProvidersDialog.vue")['default']
    'PricingPlanDialog': typeof import("../components/dialogs/PricingPlanDialog.vue")['default']
    'ReferAndEarnDialog': typeof import("../components/dialogs/ReferAndEarnDialog.vue")['default']
    'ShareProjectDialog': typeof import("../components/dialogs/ShareProjectDialog.vue")['default']
    'TwoFactorAuthDialog': typeof import("../components/dialogs/TwoFactorAuthDialog.vue")['default']
    'UserInfoEditDialog': typeof import("../components/dialogs/UserInfoEditDialog.vue")['default']
    'UserUpgradePlanDialog': typeof import("../components/dialogs/UserUpgradePlanDialog.vue")['default']
    'NodeMarketList': typeof import("../components/nodeMarketList.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.1.1_@vue+compiler-dom@3.5.13_eslint@9.18.0_jiti@2.4.2__magicast@0.3.5_rollup@4_nebyfme3wwny6njuwiow22hq24/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.1.1_@vue+compiler-dom@3.5.13_eslint@9.18.0_jiti@2.4.2__magicast@0.3.5_rollup@4_nebyfme3wwny6njuwiow22hq24/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'VueApexCharts': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAppBarSearch': typeof import("../@core/components/AppBarSearch.vue")['default']
    'LazyAppDrawerHeaderSection': typeof import("../@core/components/AppDrawerHeaderSection.vue")['default']
    'LazyAppStepper': typeof import("../@core/components/AppStepper.vue")['default']
    'LazyBuyNow': typeof import("../@core/components/BuyNow.vue")['default']
    'LazyCardStatisticsVerticalSimple': typeof import("../@core/components/CardStatisticsVerticalSimple.vue")['default']
    'LazyCustomizerSection': typeof import("../@core/components/CustomizerSection.vue")['default']
    'LazyDialogCloseBtn': typeof import("../@core/components/DialogCloseBtn.vue")['default']
    'LazyDropZone': typeof import("../@core/components/DropZone.vue")['default']
    'LazyI18n': typeof import("../@core/components/I18n.vue")['default']
    'LazyMoreBtn': typeof import("../@core/components/MoreBtn.vue")['default']
    'LazyNotifications': typeof import("../@core/components/Notifications.vue")['default']
    'LazyProductDescriptionEditor': typeof import("../@core/components/ProductDescriptionEditor.vue")['default']
    'LazyScrollToTop': typeof import("../@core/components/ScrollToTop.vue")['default']
    'LazyShortcuts': typeof import("../@core/components/Shortcuts.vue")['default']
    'LazyTablePagination': typeof import("../@core/components/TablePagination.vue")['default']
    'LazyTheCustomizer': typeof import("../@core/components/TheCustomizer.vue")['default']
    'LazyThemeSwitcher': typeof import("../@core/components/ThemeSwitcher.vue")['default']
    'LazyTiptapEditor': typeof import("../@core/components/TiptapEditor.vue")['default']
    'LazyAppAutocomplete': typeof import("../@core/components/app-form-elements/AppAutocomplete.vue")['default']
    'LazyAppCombobox': typeof import("../@core/components/app-form-elements/AppCombobox.vue")['default']
    'LazyAppDateTimePicker': typeof import("../@core/components/app-form-elements/AppDateTimePicker.vue")['default']
    'LazyAppSelect': typeof import("../@core/components/app-form-elements/AppSelect.vue")['default']
    'LazyAppTextField': typeof import("../@core/components/app-form-elements/AppTextField.vue")['default']
    'LazyAppTextarea': typeof import("../@core/components/app-form-elements/AppTextarea.vue")['default']
    'LazyCustomCheckboxes': typeof import("../@core/components/app-form-elements/CustomCheckboxes.vue")['default']
    'LazyCustomCheckboxesWithIcon': typeof import("../@core/components/app-form-elements/CustomCheckboxesWithIcon.vue")['default']
    'LazyCustomCheckboxesWithImage': typeof import("../@core/components/app-form-elements/CustomCheckboxesWithImage.vue")['default']
    'LazyCustomRadios': typeof import("../@core/components/app-form-elements/CustomRadios.vue")['default']
    'LazyCustomRadiosWithIcon': typeof import("../@core/components/app-form-elements/CustomRadiosWithIcon.vue")['default']
    'LazyAppCardActions': typeof import("../@core/components/cards/AppCardActions.vue")['default']
    'LazyAppCardCode': typeof import("../@core/components/cards/AppCardCode.vue")['default']
    'LazyCardStatisticsHorizontal': typeof import("../@core/components/cards/CardStatisticsHorizontal.vue")['default']
    'LazyCardStatisticsVertical': typeof import("../@core/components/cards/CardStatisticsVertical.vue")['default']
    'LazyAppLoadingIndicator': typeof import("../components/AppLoadingIndicator.vue")['default']
    'LazyAppPricing': typeof import("../components/AppPricing.vue")['default']
    'LazyAppSearchHeader': typeof import("../components/AppSearchHeader.vue")['default']
    'LazyErrorHeader': typeof import("../components/ErrorHeader.vue")['default']
    'LazyFormStep': typeof import("../components/FormStep.vue")['default']
    'LazyVueApexCharts': typeof import("../components/VueApexCharts.client.vue")['default']
    'LazyAddAuthenticatorAppDialog': typeof import("../components/dialogs/AddAuthenticatorAppDialog.vue")['default']
    'LazyAddEditAddressDialog': typeof import("../components/dialogs/AddEditAddressDialog.vue")['default']
    'LazyAddEditPermissionDialog': typeof import("../components/dialogs/AddEditPermissionDialog.vue")['default']
    'LazyAddEditRoleDialog': typeof import("../components/dialogs/AddEditRoleDialog.vue")['default']
    'LazyAddEditVolume': typeof import("../components/dialogs/AddEditVolume.vue")['default']
    'LazyAddKubeflowUserDialog': typeof import("../components/dialogs/AddKubeflowUserDialog.vue")['default']
    'LazyAddMOrganizationemberDialog': typeof import("../components/dialogs/AddMOrganizationemberDialog.vue")['default']
    'LazyAddPaymentMethodDialog': typeof import("../components/dialogs/AddPaymentMethodDialog.vue")['default']
    'LazyCardAddEditDialog': typeof import("../components/dialogs/CardAddEditDialog.vue")['default']
    'LazyConfirmDialog': typeof import("../components/dialogs/ConfirmDialog.vue")['default']
    'LazyCreateAppDialog': typeof import("../components/dialogs/CreateAppDialog.vue")['default']
    'LazyEnableOneTimePasswordDialog': typeof import("../components/dialogs/EnableOneTimePasswordDialog.vue")['default']
    'LazyPaymentProvidersDialog': typeof import("../components/dialogs/PaymentProvidersDialog.vue")['default']
    'LazyPricingPlanDialog': typeof import("../components/dialogs/PricingPlanDialog.vue")['default']
    'LazyReferAndEarnDialog': typeof import("../components/dialogs/ReferAndEarnDialog.vue")['default']
    'LazyShareProjectDialog': typeof import("../components/dialogs/ShareProjectDialog.vue")['default']
    'LazyTwoFactorAuthDialog': typeof import("../components/dialogs/TwoFactorAuthDialog.vue")['default']
    'LazyUserInfoEditDialog': typeof import("../components/dialogs/UserInfoEditDialog.vue")['default']
    'LazyUserUpgradePlanDialog': typeof import("../components/dialogs/UserUpgradePlanDialog.vue")['default']
    'LazyNodeMarketList': typeof import("../components/nodeMarketList.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.1.1_@vue+compiler-dom@3.5.13_eslint@9.18.0_jiti@2.4.2__magicast@0.3.5_rollup@4_nebyfme3wwny6njuwiow22hq24/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.1.1_@vue+compiler-dom@3.5.13_eslint@9.18.0_jiti@2.4.2__magicast@0.3.5_rollup@4_nebyfme3wwny6njuwiow22hq24/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyVueApexCharts': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AppBarSearch: typeof import("../@core/components/AppBarSearch.vue")['default']
export const AppDrawerHeaderSection: typeof import("../@core/components/AppDrawerHeaderSection.vue")['default']
export const AppStepper: typeof import("../@core/components/AppStepper.vue")['default']
export const BuyNow: typeof import("../@core/components/BuyNow.vue")['default']
export const CardStatisticsVerticalSimple: typeof import("../@core/components/CardStatisticsVerticalSimple.vue")['default']
export const CustomizerSection: typeof import("../@core/components/CustomizerSection.vue")['default']
export const DialogCloseBtn: typeof import("../@core/components/DialogCloseBtn.vue")['default']
export const DropZone: typeof import("../@core/components/DropZone.vue")['default']
export const I18n: typeof import("../@core/components/I18n.vue")['default']
export const MoreBtn: typeof import("../@core/components/MoreBtn.vue")['default']
export const Notifications: typeof import("../@core/components/Notifications.vue")['default']
export const ProductDescriptionEditor: typeof import("../@core/components/ProductDescriptionEditor.vue")['default']
export const ScrollToTop: typeof import("../@core/components/ScrollToTop.vue")['default']
export const Shortcuts: typeof import("../@core/components/Shortcuts.vue")['default']
export const TablePagination: typeof import("../@core/components/TablePagination.vue")['default']
export const TheCustomizer: typeof import("../@core/components/TheCustomizer.vue")['default']
export const ThemeSwitcher: typeof import("../@core/components/ThemeSwitcher.vue")['default']
export const TiptapEditor: typeof import("../@core/components/TiptapEditor.vue")['default']
export const AppAutocomplete: typeof import("../@core/components/app-form-elements/AppAutocomplete.vue")['default']
export const AppCombobox: typeof import("../@core/components/app-form-elements/AppCombobox.vue")['default']
export const AppDateTimePicker: typeof import("../@core/components/app-form-elements/AppDateTimePicker.vue")['default']
export const AppSelect: typeof import("../@core/components/app-form-elements/AppSelect.vue")['default']
export const AppTextField: typeof import("../@core/components/app-form-elements/AppTextField.vue")['default']
export const AppTextarea: typeof import("../@core/components/app-form-elements/AppTextarea.vue")['default']
export const CustomCheckboxes: typeof import("../@core/components/app-form-elements/CustomCheckboxes.vue")['default']
export const CustomCheckboxesWithIcon: typeof import("../@core/components/app-form-elements/CustomCheckboxesWithIcon.vue")['default']
export const CustomCheckboxesWithImage: typeof import("../@core/components/app-form-elements/CustomCheckboxesWithImage.vue")['default']
export const CustomRadios: typeof import("../@core/components/app-form-elements/CustomRadios.vue")['default']
export const CustomRadiosWithIcon: typeof import("../@core/components/app-form-elements/CustomRadiosWithIcon.vue")['default']
export const AppCardActions: typeof import("../@core/components/cards/AppCardActions.vue")['default']
export const AppCardCode: typeof import("../@core/components/cards/AppCardCode.vue")['default']
export const CardStatisticsHorizontal: typeof import("../@core/components/cards/CardStatisticsHorizontal.vue")['default']
export const CardStatisticsVertical: typeof import("../@core/components/cards/CardStatisticsVertical.vue")['default']
export const AppLoadingIndicator: typeof import("../components/AppLoadingIndicator.vue")['default']
export const AppPricing: typeof import("../components/AppPricing.vue")['default']
export const AppSearchHeader: typeof import("../components/AppSearchHeader.vue")['default']
export const ErrorHeader: typeof import("../components/ErrorHeader.vue")['default']
export const FormStep: typeof import("../components/FormStep.vue")['default']
export const VueApexCharts: typeof import("../components/VueApexCharts.client.vue")['default']
export const AddAuthenticatorAppDialog: typeof import("../components/dialogs/AddAuthenticatorAppDialog.vue")['default']
export const AddEditAddressDialog: typeof import("../components/dialogs/AddEditAddressDialog.vue")['default']
export const AddEditPermissionDialog: typeof import("../components/dialogs/AddEditPermissionDialog.vue")['default']
export const AddEditRoleDialog: typeof import("../components/dialogs/AddEditRoleDialog.vue")['default']
export const AddEditVolume: typeof import("../components/dialogs/AddEditVolume.vue")['default']
export const AddKubeflowUserDialog: typeof import("../components/dialogs/AddKubeflowUserDialog.vue")['default']
export const AddMOrganizationemberDialog: typeof import("../components/dialogs/AddMOrganizationemberDialog.vue")['default']
export const AddPaymentMethodDialog: typeof import("../components/dialogs/AddPaymentMethodDialog.vue")['default']
export const CardAddEditDialog: typeof import("../components/dialogs/CardAddEditDialog.vue")['default']
export const ConfirmDialog: typeof import("../components/dialogs/ConfirmDialog.vue")['default']
export const CreateAppDialog: typeof import("../components/dialogs/CreateAppDialog.vue")['default']
export const EnableOneTimePasswordDialog: typeof import("../components/dialogs/EnableOneTimePasswordDialog.vue")['default']
export const PaymentProvidersDialog: typeof import("../components/dialogs/PaymentProvidersDialog.vue")['default']
export const PricingPlanDialog: typeof import("../components/dialogs/PricingPlanDialog.vue")['default']
export const ReferAndEarnDialog: typeof import("../components/dialogs/ReferAndEarnDialog.vue")['default']
export const ShareProjectDialog: typeof import("../components/dialogs/ShareProjectDialog.vue")['default']
export const TwoFactorAuthDialog: typeof import("../components/dialogs/TwoFactorAuthDialog.vue")['default']
export const UserInfoEditDialog: typeof import("../components/dialogs/UserInfoEditDialog.vue")['default']
export const UserUpgradePlanDialog: typeof import("../components/dialogs/UserUpgradePlanDialog.vue")['default']
export const NodeMarketList: typeof import("../components/nodeMarketList.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.1.1_@vue+compiler-dom@3.5.13_eslint@9.18.0_jiti@2.4.2__magicast@0.3.5_rollup@4_nebyfme3wwny6njuwiow22hq24/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.1.1_@vue+compiler-dom@3.5.13_eslint@9.18.0_jiti@2.4.2__magicast@0.3.5_rollup@4_nebyfme3wwny6njuwiow22hq24/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const VueApexCharts: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAppBarSearch: typeof import("../@core/components/AppBarSearch.vue")['default']
export const LazyAppDrawerHeaderSection: typeof import("../@core/components/AppDrawerHeaderSection.vue")['default']
export const LazyAppStepper: typeof import("../@core/components/AppStepper.vue")['default']
export const LazyBuyNow: typeof import("../@core/components/BuyNow.vue")['default']
export const LazyCardStatisticsVerticalSimple: typeof import("../@core/components/CardStatisticsVerticalSimple.vue")['default']
export const LazyCustomizerSection: typeof import("../@core/components/CustomizerSection.vue")['default']
export const LazyDialogCloseBtn: typeof import("../@core/components/DialogCloseBtn.vue")['default']
export const LazyDropZone: typeof import("../@core/components/DropZone.vue")['default']
export const LazyI18n: typeof import("../@core/components/I18n.vue")['default']
export const LazyMoreBtn: typeof import("../@core/components/MoreBtn.vue")['default']
export const LazyNotifications: typeof import("../@core/components/Notifications.vue")['default']
export const LazyProductDescriptionEditor: typeof import("../@core/components/ProductDescriptionEditor.vue")['default']
export const LazyScrollToTop: typeof import("../@core/components/ScrollToTop.vue")['default']
export const LazyShortcuts: typeof import("../@core/components/Shortcuts.vue")['default']
export const LazyTablePagination: typeof import("../@core/components/TablePagination.vue")['default']
export const LazyTheCustomizer: typeof import("../@core/components/TheCustomizer.vue")['default']
export const LazyThemeSwitcher: typeof import("../@core/components/ThemeSwitcher.vue")['default']
export const LazyTiptapEditor: typeof import("../@core/components/TiptapEditor.vue")['default']
export const LazyAppAutocomplete: typeof import("../@core/components/app-form-elements/AppAutocomplete.vue")['default']
export const LazyAppCombobox: typeof import("../@core/components/app-form-elements/AppCombobox.vue")['default']
export const LazyAppDateTimePicker: typeof import("../@core/components/app-form-elements/AppDateTimePicker.vue")['default']
export const LazyAppSelect: typeof import("../@core/components/app-form-elements/AppSelect.vue")['default']
export const LazyAppTextField: typeof import("../@core/components/app-form-elements/AppTextField.vue")['default']
export const LazyAppTextarea: typeof import("../@core/components/app-form-elements/AppTextarea.vue")['default']
export const LazyCustomCheckboxes: typeof import("../@core/components/app-form-elements/CustomCheckboxes.vue")['default']
export const LazyCustomCheckboxesWithIcon: typeof import("../@core/components/app-form-elements/CustomCheckboxesWithIcon.vue")['default']
export const LazyCustomCheckboxesWithImage: typeof import("../@core/components/app-form-elements/CustomCheckboxesWithImage.vue")['default']
export const LazyCustomRadios: typeof import("../@core/components/app-form-elements/CustomRadios.vue")['default']
export const LazyCustomRadiosWithIcon: typeof import("../@core/components/app-form-elements/CustomRadiosWithIcon.vue")['default']
export const LazyAppCardActions: typeof import("../@core/components/cards/AppCardActions.vue")['default']
export const LazyAppCardCode: typeof import("../@core/components/cards/AppCardCode.vue")['default']
export const LazyCardStatisticsHorizontal: typeof import("../@core/components/cards/CardStatisticsHorizontal.vue")['default']
export const LazyCardStatisticsVertical: typeof import("../@core/components/cards/CardStatisticsVertical.vue")['default']
export const LazyAppLoadingIndicator: typeof import("../components/AppLoadingIndicator.vue")['default']
export const LazyAppPricing: typeof import("../components/AppPricing.vue")['default']
export const LazyAppSearchHeader: typeof import("../components/AppSearchHeader.vue")['default']
export const LazyErrorHeader: typeof import("../components/ErrorHeader.vue")['default']
export const LazyFormStep: typeof import("../components/FormStep.vue")['default']
export const LazyVueApexCharts: typeof import("../components/VueApexCharts.client.vue")['default']
export const LazyAddAuthenticatorAppDialog: typeof import("../components/dialogs/AddAuthenticatorAppDialog.vue")['default']
export const LazyAddEditAddressDialog: typeof import("../components/dialogs/AddEditAddressDialog.vue")['default']
export const LazyAddEditPermissionDialog: typeof import("../components/dialogs/AddEditPermissionDialog.vue")['default']
export const LazyAddEditRoleDialog: typeof import("../components/dialogs/AddEditRoleDialog.vue")['default']
export const LazyAddEditVolume: typeof import("../components/dialogs/AddEditVolume.vue")['default']
export const LazyAddKubeflowUserDialog: typeof import("../components/dialogs/AddKubeflowUserDialog.vue")['default']
export const LazyAddMOrganizationemberDialog: typeof import("../components/dialogs/AddMOrganizationemberDialog.vue")['default']
export const LazyAddPaymentMethodDialog: typeof import("../components/dialogs/AddPaymentMethodDialog.vue")['default']
export const LazyCardAddEditDialog: typeof import("../components/dialogs/CardAddEditDialog.vue")['default']
export const LazyConfirmDialog: typeof import("../components/dialogs/ConfirmDialog.vue")['default']
export const LazyCreateAppDialog: typeof import("../components/dialogs/CreateAppDialog.vue")['default']
export const LazyEnableOneTimePasswordDialog: typeof import("../components/dialogs/EnableOneTimePasswordDialog.vue")['default']
export const LazyPaymentProvidersDialog: typeof import("../components/dialogs/PaymentProvidersDialog.vue")['default']
export const LazyPricingPlanDialog: typeof import("../components/dialogs/PricingPlanDialog.vue")['default']
export const LazyReferAndEarnDialog: typeof import("../components/dialogs/ReferAndEarnDialog.vue")['default']
export const LazyShareProjectDialog: typeof import("../components/dialogs/ShareProjectDialog.vue")['default']
export const LazyTwoFactorAuthDialog: typeof import("../components/dialogs/TwoFactorAuthDialog.vue")['default']
export const LazyUserInfoEditDialog: typeof import("../components/dialogs/UserInfoEditDialog.vue")['default']
export const LazyUserUpgradePlanDialog: typeof import("../components/dialogs/UserUpgradePlanDialog.vue")['default']
export const LazyNodeMarketList: typeof import("../components/nodeMarketList.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.1.1_@vue+compiler-dom@3.5.13_eslint@9.18.0_jiti@2.4.2__magicast@0.3.5_rollup@4_nebyfme3wwny6njuwiow22hq24/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@9.1.1_@vue+compiler-dom@3.5.13_eslint@9.18.0_jiti@2.4.2__magicast@0.3.5_rollup@4_nebyfme3wwny6njuwiow22hq24/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyVueApexCharts: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.15.2_@parcel+watcher@2.5.0_@types+node@22.10.7_db0@0.2.1_eslint@9.18.0_jiti@2.4.2__ior_tqrvnbz6pw3kmf25rli7msebxy/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
