/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Condition holds the information about the state of a resource.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1Condition { 
    /**
     * Well-defined error codes in case the condition reports a problem.
     */
    codes?: Array<string>;
    /**
     * Last time the condition transitioned from one status to another.
     */
    lastTransitionTime: string;
    /**
     * Last time the condition was updated.
     */
    lastUpdateTime: string;
    /**
     * A human readable message indicating details about the transition.
     */
    message: string;
    /**
     * The reason for the condition\'s last transition.
     */
    reason: string;
    /**
     * Status of the condition, one of True, False, Unknown.
     */
    status: string;
    /**
     * Type of the condition.
     */
    type: string;
}

