/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IoK8sApiCoreV1SecretReference } from './ioK8sApiCoreV1SecretReference';
import { ComGithubGardenerGardenerPkgApisCoreV1beta1BackupBucketProvider } from './comGithubGardenerGardenerPkgApisCoreV1beta1BackupBucketProvider';


/**
 * BackupBucketSpec is the specification of a Backup Bucket.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1BackupBucketSpec { 
    /**
     * Provider holds the details of cloud provider of the object store. This field is immutable.
     */
    provider: ComGithubGardenerGardenerPkgApisCoreV1beta1BackupBucketProvider;
    /**
     * ProviderConfig is the configuration passed to BackupBucket resource.
     */
    providerConfig?: object;
    /**
     * SecretRef is a reference to a secret that contains the credentials to access object store.
     */
    secretRef: IoK8sApiCoreV1SecretReference;
    /**
     * SeedName holds the name of the seed allocated to BackupBucket for running controller. This field is immutable.
     */
    seedName?: string;
}

