/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComGithubGardenerGardenerPkgApisCoreV1beta1CRI } from './comGithubGardenerGardenerPkgApisCoreV1beta1CRI';


/**
 * MachineImageVersion is an expirable version with list of supported container runtimes and interfaces
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1MachineImageVersion { 
    /**
     * Architectures is the list of CPU architectures of the machine image in this version.
     */
    architectures?: Array<string>;
    /**
     * Classification defines the state of a version (preview, supported, deprecated)
     */
    classification?: string;
    /**
     * CRI list of supported container runtime and interfaces supported by this version
     */
    cri?: Array<ComGithubGardenerGardenerPkgApisCoreV1beta1CRI>;
    /**
     * ExpirationDate defines the time at which this version expires.
     */
    expirationDate?: string;
    /**
     * KubeletVersionConstraint is a constraint describing the supported kubelet versions by the machine image in this version. If the field is not specified, it is assumed that the machine image in this version supports all kubelet versions. Examples: - \'>= 1.26\' - supports only kubelet versions greater than or equal to 1.26 - \'< 1.26\' - supports only kubelet versions less than 1.26
     */
    kubeletVersionConstraint?: string;
    /**
     * Version is the version identifier.
     */
    version: string;
}

