/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComGithubGardenerGardenerPkgApisCoreV1beta1Alerting } from './comGithubGardenerGardenerPkgApisCoreV1beta1Alerting';


/**
 * Monitoring contains information about the monitoring configuration for the shoot.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1Monitoring { 
    /**
     * Alerting contains information about the alerting configuration for the shoot cluster.
     */
    alerting?: ComGithubGardenerGardenerPkgApisCoreV1beta1Alerting;
}

