/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * FailureTolerance describes information about failure tolerance level of a highly available resource.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1FailureTolerance { 
    /**
     * Type specifies the type of failure that the highly available resource can tolerate
     */
    type: string;
}

