/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ViewerKubeconfigRequestSpec contains the expiration time of the kubeconfig.
 */
export interface ComGithubGardenerGardenerPkgApisAuthenticationV1alpha1ViewerKubeconfigRequestSpec { 
    /**
     * ExpirationSeconds is the requested validity duration of the credential. The credential issuer may return a credential with a different validity duration so a client needs to check the \'expirationTimestamp\' field in a response. Defaults to 1 hour.
     */
    expirationSeconds?: number;
}

