/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SSHAccess contains settings regarding ssh access to the worker nodes.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1SSHAccess { 
    /**
     * Enabled indicates whether the SSH access to the worker nodes is ensured to be enabled or disabled in systemd. Defaults to true.
     */
    enabled: boolean;
}

