/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ContainerRuntime contains information about worker\'s available container runtime
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1ContainerRuntime { 
    /**
     * ProviderConfig is the configuration passed to container runtime resource.
     */
    providerConfig?: object;
    /**
     * Type is the type of the Container Runtime.
     */
    type: string;
}

