/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * MemorySwapConfiguration contains kubelet swap configuration For more information, please see KEP: 2400-node-swap
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1MemorySwapConfiguration { 
    /**
     * SwapBehavior configures swap memory available to container workloads. May be one of {\"LimitedSwap\", \"UnlimitedSwap\"} defaults to: LimitedSwap
     */
    swapBehavior?: string;
}

