/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * VerticalPodAutoscaler contains the configuration flags for the Kubernetes vertical pod autoscaler.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1VerticalPodAutoscaler { 
    /**
     * Enabled specifies whether the Kubernetes VPA shall be enabled for the shoot cluster.
     */
    enabled: boolean;
    /**
     * EvictAfterOOMThreshold defines the threshold that will lead to pod eviction in case it OOMed in less than the given threshold since its start and if it has only one container (default: 10m0s).
     */
    evictAfterOOMThreshold?: string;
    /**
     * EvictionRateBurst defines the burst of pods that can be evicted (default: 1)
     */
    evictionRateBurst?: number;
    /**
     * EvictionRateLimit defines the number of pods that can be evicted per second. A rate limit set to 0 or -1 will disable the rate limiter (default: -1).
     */
    evictionRateLimit?: number;
    /**
     * EvictionTolerance defines the fraction of replica count that can be evicted for update in case more than one pod can be evicted (default: 0.5).
     */
    evictionTolerance?: number;
    /**
     * RecommendationMarginFraction is the fraction of usage added as the safety margin to the recommended request (default: 0.15).
     */
    recommendationMarginFraction?: number;
    /**
     * RecommenderInterval is the interval how often metrics should be fetched (default: 1m0s).
     */
    recommenderInterval?: string;
    /**
     * TargetCPUPercentile is the usage percentile that will be used as a base for CPU target recommendation. Doesn\'t affect CPU lower bound, CPU upper bound nor memory recommendations. (default: 0.9)
     */
    targetCPUPercentile?: number;
    /**
     * UpdaterInterval is the interval how often the updater should run (default: 1m0s).
     */
    updaterInterval?: string;
}

