/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComGithubGardenerGardenerPkgApisCoreV1OCIRepository } from './comGithubGardenerGardenerPkgApisCoreV1OCIRepository';


/**
 * HelmControllerDeployment configures how an extension controller is deployed using helm.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1HelmControllerDeployment { 
    /**
     * OCIRepository defines where to pull the chart.
     */
    ociRepository?: ComGithubGardenerGardenerPkgApisCoreV1OCIRepository;
    /**
     * RawChart is the base64-encoded, gzip\'ed, tar\'ed extension controller chart.
     */
    rawChart?: string;
    /**
     * Values are the chart values.
     */
    values?: any | null;
}

