/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * CoreDNSRewriting contains the setting related to rewriting requests, which are obviously incorrect due to the unnecessary application of the search path.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1CoreDNSRewriting { 
    /**
     * CommonSuffixes are expected to be the suffix of a fully qualified domain name. Each suffix should contain at least one or two dots (\'.\') to prevent accidental clashes.
     */
    commonSuffixes?: Array<string>;
}

