/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComGithubGardenerGardenerPkgApisCoreV1beta1NginxIngress } from './comGithubGardenerGardenerPkgApisCoreV1beta1NginxIngress';
import { ComGithubGardenerGardenerPkgApisCoreV1beta1KubernetesDashboard } from './comGithubGardenerGardenerPkgApisCoreV1beta1KubernetesDashboard';


/**
 * Addons is a collection of configuration for specific addons which are managed by the Gardener.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1Addons { 
    /**
     * KubernetesDashboard holds configuration settings for the kubernetes dashboard addon.
     */
    kubernetesDashboard?: ComGithubGardenerGardenerPkgApisCoreV1beta1KubernetesDashboard;
    /**
     * NginxIngress holds configuration settings for the nginx-ingress addon.
     */
    nginxIngress?: ComGithubGardenerGardenerPkgApisCoreV1beta1NginxIngress;
}

