/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ETCDEncryptionKeyRotation contains information about the ETCD encryption key credential rotation.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1ETCDEncryptionKeyRotation { 
    /**
     * LastCompletionTime is the most recent time when the ETCD encryption key credential rotation was successfully completed.
     */
    lastCompletionTime?: string;
    /**
     * LastCompletionTriggeredTime is the recent time when the certificate authority credential rotation completion was triggered.
     */
    lastCompletionTriggeredTime?: string;
    /**
     * LastInitiationFinishedTime is the recent time when the certificate authority credential rotation initiation was completed.
     */
    lastInitiationFinishedTime?: string;
    /**
     * LastInitiationTime is the most recent time when the ETCD encryption key credential rotation was initiated.
     */
    lastInitiationTime?: string;
    /**
     * Phase describes the phase of the ETCD encryption key credential rotation.
     */
    phase: string;
}

