/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ProjectStatus holds the most recently observed status of the project.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1ProjectStatus { 
    /**
     * LastActivityTimestamp contains the timestamp from the last activity performed in this project.
     */
    lastActivityTimestamp?: string;
    /**
     * ObservedGeneration is the most recent generation observed for this project.
     */
    observedGeneration?: number;
    /**
     * Phase is the current phase of the project.
     */
    phase?: string;
    /**
     * StaleAutoDeleteTimestamp contains the timestamp when the project will be garbage-collected/automatically deleted because it\'s stale/unused.
     */
    staleAutoDeleteTimestamp?: string;
    /**
     * StaleSinceTimestamp contains the timestamp when the project was first discovered to be stale/unused.
     */
    staleSinceTimestamp?: string;
}

