/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ResourceWatchCacheSize contains configuration of the API server\'s watch cache size for one specific resource.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1ResourceWatchCacheSize { 
    /**
     * APIGroup is the API group of the resource for which the watch cache size should be configured. An unset value is used to specify the legacy core API (e.g. for `secrets`).
     */
    apiGroup?: string;
    /**
     * Resource is the name of the resource for which the watch cache size should be configured (in lowercase plural form, e.g. `secrets`).
     */
    resource: string;
    /**
     * CacheSize specifies the watch cache size that should be configured for the specified resource.
     */
    size: number;
}

