/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * BackupEntrySpec is the specification of a Backup Entry.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1BackupEntrySpec { 
    /**
     * BucketName is the name of backup bucket for this Backup Entry.
     */
    bucketName: string;
    /**
     * SeedName holds the name of the seed to which this BackupEntry is scheduled
     */
    seedName?: string;
}

