/**
 * Gardener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.98.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * APIServerRequests contains configuration for request-specific settings for the kube-apiserver.
 */
export interface ComGithubGardenerGardenerPkgApisCoreV1beta1APIServerRequests { 
    /**
     * MaxMutatingInflight is the maximum number of mutating requests in flight at a given time. When the server exceeds this, it rejects requests.
     */
    maxMutatingInflight?: number;
    /**
     * MaxNonMutatingInflight is the maximum number of non-mutating requests in flight at a given time. When the server exceeds this, it rejects requests.
     */
    maxNonMutatingInflight?: number;
}

