/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection { 
    authenticatorAttachment?: ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection.AuthenticatorAttachmentEnum;
    requireResidentKey?: boolean;
    residentKey?: ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection.ResidentKeyEnum;
    userVerification?: ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection.UserVerificationEnum;
}
export namespace ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection {
    export type AuthenticatorAttachmentEnum = 'platform' | 'cross-platform';
    export const AuthenticatorAttachmentEnum = {
        Platform: 'platform' as AuthenticatorAttachmentEnum,
        CrossPlatform: 'cross-platform' as AuthenticatorAttachmentEnum
    };
    export type ResidentKeyEnum = 'discouraged' | 'preferred' | 'required';
    export const ResidentKeyEnum = {
        Discouraged: 'discouraged' as ResidentKeyEnum,
        Preferred: 'preferred' as ResidentKeyEnum,
        Required: 'required' as ResidentKeyEnum
    };
    export type UserVerificationEnum = 'required' | 'preferred' | 'discouraged';
    export const UserVerificationEnum = {
        Required: 'required' as UserVerificationEnum,
        Preferred: 'preferred' as UserVerificationEnum,
        Discouraged: 'discouraged' as UserVerificationEnum
    };
}


