/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateConnectorTestRequest { 
    /**
     * Phone number to send test message to. If this is set, email will be ignored.
     */
    phone?: string;
    /**
     * Email address to send test message to. If phone is set, this will be ignored.
     */
    email?: string;
    /**
     * Connector configuration object for testing.
     */
    config: object;
}

