/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateApplicationUserConsentScopeRequest { 
    /**
     * A list of organization scope id to assign to the application. Throws error if any given organization scope is not found.
     */
    organizationScopes?: Array<string>;
    /**
     * A list of resource scope id to assign to the application. Throws error if any given resource scope is not found.
     */
    resourceScopes?: Array<string>;
    /**
     * A list of organization resource scope id to assign to the application. Throws error if any given resource scope is not found.
     */
    organizationResourceScopes?: Array<string>;
    /**
     * A list of user scope enum value to assign to the application.
     */
    userScopes?: Array<CreateApplicationUserConsentScopeRequest.UserScopesEnum>;
}
export namespace CreateApplicationUserConsentScopeRequest {
    export type UserScopesEnum = 'profile' | 'email' | 'phone' | 'address' | 'custom_data' | 'identities' | 'roles' | 'urn:logto:scope:organizations' | 'urn:logto:scope:organization_roles';
    export const UserScopesEnum = {
        Profile: 'profile' as UserScopesEnum,
        Email: 'email' as UserScopesEnum,
        Phone: 'phone' as UserScopesEnum,
        Address: 'address' as UserScopesEnum,
        CustomData: 'custom_data' as UserScopesEnum,
        Identities: 'identities' as UserScopesEnum,
        Roles: 'roles' as UserScopesEnum,
        Urnlogtoscopeorganizations: 'urn:logto:scope:organizations' as UserScopesEnum,
        UrnlogtoscopeorganizationRoles: 'urn:logto:scope:organization_roles' as UserScopesEnum
    };
}


