/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiInteractionConsentGet200ResponseApplicationBranding } from './apiInteractionConsentGet200ResponseApplicationBranding';


export interface GetApplicationSignInExperience200Response { 
    tenantId: string;
    applicationId: string;
    branding: ApiInteractionConsentGet200ResponseApplicationBranding;
    termsOfUseUrl: string | null;
    privacyPolicyUrl: string | null;
    displayName: string | null;
}

