/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetJwtCustomizer200ResponseOneOf1 } from './getJwtCustomizer200ResponseOneOf1';
import { GetJwtCustomizer200ResponseOneOf } from './getJwtCustomizer200ResponseOneOf';
import { GetJwtCustomizer200ResponseOneOf1TokenSample } from './getJwtCustomizer200ResponseOneOf1TokenSample';


/**
 * @type GetJwtCustomizer200Response
 * @export
 */
export type GetJwtCustomizer200Response = GetJwtCustomizer200ResponseOneOf | GetJwtCustomizer200ResponseOneOf1;

