/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetOrganizationRole200Response { 
    tenantId: string;
    id: string;
    name: string;
    description: string | null;
    type: GetOrganizationRole200Response.TypeEnum;
}
export namespace GetOrganizationRole200Response {
    export type TypeEnum = 'User' | 'MachineToMachine';
    export const TypeEnum = {
        User: 'User' as TypeEnum,
        MachineToMachine: 'MachineToMachine' as TypeEnum
    };
}


