/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListApplicationOrganizations200ResponseInnerOrganizationRolesInner } from './listApplicationOrganizations200ResponseInnerOrganizationRolesInner';


export interface GetOrganizationInvitation200Response { 
    tenantId: string;
    id: string;
    inviterId: string | null;
    invitee: string;
    acceptedUserId: string | null;
    organizationId: string;
    status: GetOrganizationInvitation200Response.StatusEnum;
    createdAt: number;
    updatedAt: number;
    expiresAt: number;
    organizationRoles: Array<ListApplicationOrganizations200ResponseInnerOrganizationRolesInner>;
}
export namespace GetOrganizationInvitation200Response {
    export type StatusEnum = 'Pending' | 'Accepted' | 'Expired' | 'Revoked';
    export const StatusEnum = {
        Pending: 'Pending' as StatusEnum,
        Accepted: 'Accepted' as StatusEnum,
        Expired: 'Expired' as StatusEnum,
        Revoked: 'Revoked' as StatusEnum
    };
}


