/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSignInExp200ResponseLanguageInfo } from './getSignInExp200ResponseLanguageInfo';
import { GetSignInExp200ResponseSignUp } from './getSignInExp200ResponseSignUp';
import { ApiInteractionConsentGet200ResponseApplicationBranding } from './apiInteractionConsentGet200ResponseApplicationBranding';
import { GetSignInExp200ResponseSignIn } from './getSignInExp200ResponseSignIn';
import { GetSignInExp200ResponseMfa } from './getSignInExp200ResponseMfa';
import { GetSignInExp200ResponseSocialSignIn } from './getSignInExp200ResponseSocialSignIn';
import { GetSignInExp200ResponsePasswordPolicy } from './getSignInExp200ResponsePasswordPolicy';
import { GetSignInExp200ResponseColor } from './getSignInExp200ResponseColor';


export interface GetSignInExp200Response { 
    tenantId: string;
    id: string;
    color: GetSignInExp200ResponseColor;
    branding: ApiInteractionConsentGet200ResponseApplicationBranding;
    languageInfo: GetSignInExp200ResponseLanguageInfo;
    termsOfUseUrl: string | null;
    privacyPolicyUrl: string | null;
    agreeToTermsPolicy: GetSignInExp200Response.AgreeToTermsPolicyEnum;
    signIn: GetSignInExp200ResponseSignIn;
    signUp: GetSignInExp200ResponseSignUp;
    socialSignIn: GetSignInExp200ResponseSocialSignIn;
    /**
     * Enabled social sign-in connectors, will displayed on the sign-in page.
     */
    socialSignInConnectorTargets: Array<string>;
    signInMode: GetSignInExp200Response.SignInModeEnum;
    customCss: string | null;
    /**
     * Custom content to display on experience flow pages. the page pathname will be the config key, the content will be the config value.
     */
    customContent: { [key: string]: string; };
    customUiAssetId: string | null;
    passwordPolicy: GetSignInExp200ResponsePasswordPolicy;
    mfa: GetSignInExp200ResponseMfa;
    singleSignOnEnabled: boolean;
}
export namespace GetSignInExp200Response {
    export type AgreeToTermsPolicyEnum = 'Automatic' | 'ManualRegistrationOnly' | 'Manual';
    export const AgreeToTermsPolicyEnum = {
        Automatic: 'Automatic' as AgreeToTermsPolicyEnum,
        ManualRegistrationOnly: 'ManualRegistrationOnly' as AgreeToTermsPolicyEnum,
        Manual: 'Manual' as AgreeToTermsPolicyEnum
    };
    export type SignInModeEnum = 'SignIn' | 'Register' | 'SignInAndRegister';
    export const SignInModeEnum = {
        SignIn: 'SignIn' as SignInModeEnum,
        Register: 'Register' as SignInModeEnum,
        SignInAndRegister: 'SignInAndRegister' as SignInModeEnum
    };
}


