/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The primary branding color for the sign-in page (both light/dark mode).
 */
export interface GetSignInExp200ResponseColor { 
    primaryColor: string;
    isDarkModeEnabled: boolean;
    darkPrimaryColor: string;
}

