/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * MFA settings
 */
export interface GetSignInExp200ResponseMfa { 
    factors: Array<GetSignInExp200ResponseMfa.FactorsEnum>;
    policy: GetSignInExp200ResponseMfa.PolicyEnum;
}
export namespace GetSignInExp200ResponseMfa {
    export type FactorsEnum = 'Totp' | 'WebAuthn' | 'BackupCode';
    export const FactorsEnum = {
        Totp: 'Totp' as FactorsEnum,
        WebAuthn: 'WebAuthn' as FactorsEnum,
        BackupCode: 'BackupCode' as FactorsEnum
    };
    export type PolicyEnum = 'UserControlled' | 'Mandatory';
    export const PolicyEnum = {
        UserControlled: 'UserControlled' as PolicyEnum,
        Mandatory: 'Mandatory' as PolicyEnum
    };
}


