/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetUserAssetServiceStatus200ResponseStatus } from './getUserAssetServiceStatus200ResponseStatus';


export interface GetUserAssetServiceStatus200Response { 
    status: GetUserAssetServiceStatus200ResponseStatus;
    allowUploadMimeTypes?: Array<GetUserAssetServiceStatus200Response.AllowUploadMimeTypesEnum>;
    maxUploadFileSize?: number;
}
export namespace GetUserAssetServiceStatus200Response {
    export type AllowUploadMimeTypesEnum = 'image/jpeg' | 'image/png' | 'image/gif' | 'image/vnd.microsoft.icon' | 'image/x-icon' | 'image/svg+xml' | 'image/tiff' | 'image/webp' | 'image/bmp';
    export const AllowUploadMimeTypesEnum = {
        Jpeg: 'image/jpeg' as AllowUploadMimeTypesEnum,
        Png: 'image/png' as AllowUploadMimeTypesEnum,
        Gif: 'image/gif' as AllowUploadMimeTypesEnum,
        VndMicrosoftIcon: 'image/vnd.microsoft.icon' as AllowUploadMimeTypesEnum,
        XIcon: 'image/x-icon' as AllowUploadMimeTypesEnum,
        Svgxml: 'image/svg+xml' as AllowUploadMimeTypesEnum,
        Tiff: 'image/tiff' as AllowUploadMimeTypesEnum,
        Webp: 'image/webp' as AllowUploadMimeTypesEnum,
        Bmp: 'image/bmp' as AllowUploadMimeTypesEnum
    };
}


