/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListConnectors200ResponseInnerFormItemsInnerOneOf2 } from './listConnectors200ResponseInnerFormItemsInnerOneOf2';
import { ListConnectors200ResponseInnerFormItemsInnerOneOf } from './listConnectors200ResponseInnerFormItemsInnerOneOf';
import { ListConnectors200ResponseInnerFormItemsInnerOneOf1 } from './listConnectors200ResponseInnerFormItemsInnerOneOf1';
import { ListConnectors200ResponseInnerFormItemsInnerOneOfShowConditionsInner } from './listConnectors200ResponseInnerFormItemsInnerOneOfShowConditionsInner';
import { ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner } from './listConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner';


/**
 * @type ListConnectors200ResponseInnerFormItemsInner
 * @export
 */
export type ListConnectors200ResponseInnerFormItemsInner = ListConnectors200ResponseInnerFormItemsInnerOneOf | ListConnectors200ResponseInnerFormItemsInnerOneOf1 | ListConnectors200ResponseInnerFormItemsInnerOneOf2;

