/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListApplications200ResponseInnerProtectedAppMetadataCustomDomainsInnerCloudflareData } from './listApplications200ResponseInnerProtectedAppMetadataCustomDomainsInnerCloudflareData';
import { ListApplications200ResponseInnerProtectedAppMetadataCustomDomainsInnerDnsRecordsInner } from './listApplications200ResponseInnerProtectedAppMetadataCustomDomainsInnerDnsRecordsInner';


export interface ListApplications200ResponseInnerProtectedAppMetadataCustomDomainsInner { 
    domain: string;
    status: ListApplications200ResponseInnerProtectedAppMetadataCustomDomainsInner.StatusEnum;
    errorMessage: string | null;
    dnsRecords: Array<ListApplications200ResponseInnerProtectedAppMetadataCustomDomainsInnerDnsRecordsInner>;
    cloudflareData: ListApplications200ResponseInnerProtectedAppMetadataCustomDomainsInnerCloudflareData | null;
}
export namespace ListApplications200ResponseInnerProtectedAppMetadataCustomDomainsInner {
    export type StatusEnum = 'PendingVerification' | 'PendingSsl' | 'Active' | 'Error';
    export const StatusEnum = {
        PendingVerification: 'PendingVerification' as StatusEnum,
        PendingSsl: 'PendingSsl' as StatusEnum,
        Active: 'Active' as StatusEnum,
        Error: 'Error' as StatusEnum
    };
}


