/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ListRoles200ResponseInnerFeaturedApplicationsInner { 
    id: string;
    name: string;
    type: ListRoles200ResponseInnerFeaturedApplicationsInner.TypeEnum;
}
export namespace ListRoles200ResponseInnerFeaturedApplicationsInner {
    export type TypeEnum = 'Native' | 'SPA' | 'Traditional' | 'MachineToMachine' | 'Protected';
    export const TypeEnum = {
        Native: 'Native' as TypeEnum,
        Spa: 'SPA' as TypeEnum,
        Traditional: 'Traditional' as TypeEnum,
        MachineToMachine: 'MachineToMachine' as TypeEnum,
        Protected: 'Protected' as TypeEnum
    };
}


