/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress } from './getJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress';


/**
 * Partial profile object to update for the given user ID.
 */
export interface UpdateUserProfileRequestProfile { 
    familyName?: string;
    givenName?: string;
    middleName?: string;
    nickname?: string;
    preferredUsername?: string;
    profile?: string;
    website?: string;
    gender?: string;
    birthdate?: string;
    zoneinfo?: string;
    locale?: string;
    address?: GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress;
}

