/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateOrganizationRoleRequest { 
    tenantId?: string;
    id?: string;
    /**
     * The updated name of the organization role. It must be unique within the organization template.
     */
    name?: string;
    /**
     * The updated description of the organization role.
     */
    description?: string | null;
    type?: UpdateOrganizationRoleRequest.TypeEnum;
}
export namespace UpdateOrganizationRoleRequest {
    export type TypeEnum = 'User' | 'MachineToMachine';
    export const TypeEnum = {
        User: 'User' as TypeEnum,
        MachineToMachine: 'MachineToMachine' as TypeEnum
    };
}


