/**
 * Logto API references
 * API references for Logto services.  Note: The documentation is for Logto Cloud. If you are using Logto OSS, please refer to the response of `/api/swagger.json` endpoint on your Logto instance.
 *
 * The version of the OpenAPI document: Cloud
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateConnectorRequestMetadata } from './updateConnectorRequestMetadata';


export interface UpdateConnectorRequest { 
    /**
     * The connector config object that will be passed to the connector. The config object should be compatible with the connector factory.
     */
    config?: object;
    metadata?: UpdateConnectorRequestMetadata;
    /**
     * Whether to sync user profile from the identity provider to Logto at each sign-in. If `false`, the user profile will only be synced when the user is created.
     */
    syncProfile?: boolean;
}

