/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InvitationService } from "../invitation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InvitationCreateInput } from "./InvitationCreateInput";
import { Invitation } from "./Invitation";
import { InvitationFindManyArgs } from "./InvitationFindManyArgs";
import { InvitationWhereUniqueInput } from "./InvitationWhereUniqueInput";
import { InvitationUpdateInput } from "./InvitationUpdateInput";
import { OrganizationMemberFindManyArgs } from "../../organizationMember/base/OrganizationMemberFindManyArgs";
import { OrganizationMember } from "../../organizationMember/base/OrganizationMember";
import { OrganizationMemberWhereUniqueInput } from "../../organizationMember/base/OrganizationMemberWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InvitationControllerBase {
  constructor(
    protected readonly service: InvitationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Invitation })
  @nestAccessControl.UseRoles({
    resource: "Invitation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInvitation(
    @common.Body() data: InvitationCreateInput
  ): Promise<Invitation> {
    return await this.service.createInvitation({
      data: {
        ...data,

        organization: {
          connect: data.organization,
        },

        inviter: {
          connect: data.inviter,
        },
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        status: true,
        expirationDate: true,

        organization: {
          select: {
            id: true,
          },
        },

        inviter: {
          select: {
            id: true,
          },
        },

        code: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Invitation] })
  @ApiNestedQuery(InvitationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Invitation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async invitations(@common.Req() request: Request): Promise<Invitation[]> {
    const args = plainToClass(InvitationFindManyArgs, request.query);
    return this.service.invitations({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        status: true,
        expirationDate: true,

        organization: {
          select: {
            id: true,
          },
        },

        inviter: {
          select: {
            id: true,
          },
        },

        code: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Invitation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Invitation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async invitation(
    @common.Param() params: InvitationWhereUniqueInput
  ): Promise<Invitation | null> {
    const result = await this.service.invitation({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        status: true,
        expirationDate: true,

        organization: {
          select: {
            id: true,
          },
        },

        inviter: {
          select: {
            id: true,
          },
        },

        code: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Invitation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Invitation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInvitation(
    @common.Param() params: InvitationWhereUniqueInput,
    @common.Body() data: InvitationUpdateInput
  ): Promise<Invitation | null> {
    try {
      return await this.service.updateInvitation({
        where: params,
        data: {
          ...data,

          organization: {
            connect: data.organization,
          },

          inviter: {
            connect: data.inviter,
          },
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          email: true,
          status: true,
          expirationDate: true,

          organization: {
            select: {
              id: true,
            },
          },

          inviter: {
            select: {
              id: true,
            },
          },

          code: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Invitation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Invitation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInvitation(
    @common.Param() params: InvitationWhereUniqueInput
  ): Promise<Invitation | null> {
    try {
      return await this.service.deleteInvitation({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          email: true,
          status: true,
          expirationDate: true,

          organization: {
            select: {
              id: true,
            },
          },

          inviter: {
            select: {
              id: true,
            },
          },

          code: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/organizationMembers")
  @ApiNestedQuery(OrganizationMemberFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OrganizationMember",
    action: "read",
    possession: "any",
  })
  async findOrganizationMembers(
    @common.Req() request: Request,
    @common.Param() params: InvitationWhereUniqueInput
  ): Promise<OrganizationMember[]> {
    const query = plainToClass(OrganizationMemberFindManyArgs, request.query);
    const results = await this.service.findOrganizationMembers(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        organization: {
          select: {
            id: true,
          },
        },

        invitation: {
          select: {
            id: true,
          },
        },

        roles: true,
        status: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/organizationMembers")
  @nestAccessControl.UseRoles({
    resource: "Invitation",
    action: "update",
    possession: "any",
  })
  async connectOrganizationMembers(
    @common.Param() params: InvitationWhereUniqueInput,
    @common.Body() body: OrganizationMemberWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      organizationMembers: {
        connect: body,
      },
    };
    await this.service.updateInvitation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/organizationMembers")
  @nestAccessControl.UseRoles({
    resource: "Invitation",
    action: "update",
    possession: "any",
  })
  async updateOrganizationMembers(
    @common.Param() params: InvitationWhereUniqueInput,
    @common.Body() body: OrganizationMemberWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      organizationMembers: {
        set: body,
      },
    };
    await this.service.updateInvitation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/organizationMembers")
  @nestAccessControl.UseRoles({
    resource: "Invitation",
    action: "update",
    possession: "any",
  })
  async disconnectOrganizationMembers(
    @common.Param() params: InvitationWhereUniqueInput,
    @common.Body() body: OrganizationMemberWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      organizationMembers: {
        disconnect: body,
      },
    };
    await this.service.updateInvitation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
